### PR TITLE
Add rule: array-function-spacing

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to add a new rule to enforce whitespace exceptions on function and array arguments and properties.

__See:__ https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#arrays-and-function-calls

__Note:__ The [base `space-in-parens` rule](http://eslint.org/docs/rules/space-in-parens#exceptions) allows exceptions for objects and arrays, which is already assigned in this project's configurations. The rule introduced here also checks functions as an exception.

__Testing:__ I found the project's `npm test` flags many lint errors incorrectly. To run the new rule's tests specifically, execute `node test/rules/array-function-spacing.js` and verify no thrown errors.

__Future Tasks:__ Add [fixer](http://eslint.org/docs/developer-guide/working-with-rules-new#applying-fixes).

># Enforce whitespace exceptions for array keys and function arguments
>
>For consistency with PHP standards, do not include a space around string literals or integers used as key values in array notation.
>
>Functions with a callback, object, or array as first or last argument should omit space respectively before or after the argument.
>
>## Rule Details
>
>The following patterns are considered warnings:
>
>```js
>foo( function() {} );
>foo( function() {});
>foo(function() {} );
>foo( () => {} );
>foo( () => {});
>foo(() => {} );
>foo( {} );
>foo( {});
>foo({} );
>foo( [] );
>foo( []);
>foo([] );
>foo(1);
>foo( 1);
>foo(1 );
>foo[ 1 ];
>foo[ 1];
>foo[1 ];
>foo[ 'bar' ];
>foo[ 'bar'];
>foo['bar' ];
>foo[ `bar` ];
>foo[ `bar`];
>foo[`bar` ];
>foo[key];
>foo[ key];
>foo[key ];
>```
>
>The following patterns are not warnings:
>
>```js
>( function( wp ) {
>	wp.foo = foo( 'bar', {});
>	wp.baz(function() {
>		console.log( 'Done' );
>	});
>} )( window.wp = window.wp || {} );
>foo(function() {});
>foo(function() {}, 1 );
>foo( 1, function() {});
>foo(() => {});
>foo(() => {}, 1 );
>foo( 1, () => {});
>foo({});
>foo({}, 1 );
>foo( 1, {});
>foo([]);
>foo([], 1 );
>foo( 1, []);
>foo( 1 );
>foo[1];
>foo['bar'];
>foo[`bar`];
>foo[ key ];
>```
>
>## Related Resources
>
>https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#arrays-and-function-calls

cc @afercia

### CODE REVIEW

**Comment by nylen** [comment]
I would rather we eliminate these spacing exceptions from the official rules.  They're extremely unintuitive, which means more things developers have to remember and spend time on, and more difficulty in validating/correcting using standard tools.  We should be going for simplicity and consistency here, IMO.

The first "valid" example in this PR is worth discussing a bit more:

```js
(function( wp ) {
  wp.foo = foo( 'bar', {});
})( window.wp = window.wp || {} );
```

- Why is `(function` special, and different than `( window.wp` or any other "opening parentheses + token" construct in the language?
- Why is `})` special, and different from `wp )` or any other "token + closing parentheses" construct in the language, including `] )`?
- There is one instance of `{})` and one instance of `{} )` in this example.  Is this correct?  What is the rule that governs whether a space appears here?
- Why would we want to write function calls with unbalanced spacing?

This should be the "valid" way to write this example:

```js
( function( wp ) {
  wp.foo = foo( 'bar', {} );
} )( window.wp = window.wp || {} );
```

We shouldn't need any specially coded rules to do this, which indicates to me that it's on the right track.  Another indication that things are "not quite right" as they stand: no other project that I've ever seen has rules like this.

**Comment by aduth** [comment]
I think I may have made a mistake on missing spaces between the callee of the IIFE (the `(function`, now corrected in 81d4bb6), but otherwise I believe the rest is correct.

>There is one instance of {}) and one instance of {} ) in this example. Is this correct? What is the rule that governs whether a space appears here?

Yes, in the first case the last argument is an `ObjectExpression` (exempted per guideline). In the latter case, the last function argument is an `AssignmentExpression`.

[Navigating the AST via AST explorer](http://astexplorer.net/#/gist/d5fee788e023fcbe02e0536c6942cf78/8911fba5e7d3b10ac0039819aac3503a52e4711f) can help clarify the nitty-gritty details.

**Comment by afercia** [comment]
> I would rather we eliminate these spacing exceptions from the official rules. 

👍

**Comment by ntwb** [comment]
Some notes, first up apologies it's taken me forever to review this, my bad, sorry.

Next up, I'm going to merge this in now, here's why:

• It's not currently "wired" up to any of the _shared  configs_ exposed by `eslint-plugin-wordpress` • Any repo's currently using `eslint-plugin-wordpress` will be unaffected by this being merged.
• I've switched locally to using Jest, I want to update the tests here to also use Jest
• I've started writing a bunch of tests for this repo and without this PR merged I'm monkey patching in each time and causing merge conflicts for myself.

By merging this I'll be able to update the tests and docs allowing for a clearer view of what is loved, and not loved so much in regard to WP's JS Coding Standards.

**Pull request merged**
